### ISSUE TITLE
SUPER RACER - Sherpa Mini Direct Drive Extruder w/LDO36STH20-1004AHG(XH

### ISSUE THREAD

**Issue by seekis** [danorder/All-In-One-V400-SR-Official-Klipper-#8]
I was using the [LGX Lite](https://github.com/danorder/Flsun-super-racer-Full-klipper-config-/blob/main/upgraded%20extruder%20configs/lgx-lite.cfg) config, but I am not sure where I am supposed to include this data within the new format. For the time being I am going to try using the stockV400 extruder profile and see how things go.

**Comment by seekis** [comment]
just edited printer.cfg, create steppers folder in ../printer_data and loaded the 24v-0.7a-e.cfg file and included it in printer.cfg.

**Comment by danorder** [comment]
p.m on facebook since it sounds like i need to just trouble shoot yours. / it'll just be quicker. and, moving he steppers shouldn't solve anything, it would mean its not seeing printer.cfg or its not seeing the right one
